export const SET_GET_SLEEP_TRACKERS_BY_USERID =
  "SET_GET_SLEEP_TRACKERS_BY_USERID";
export const SET_GET_SLEEP_TRACKERS_BY_DAYS = "SET_GET_SLEEP_TRACKERS_BY_DAYS";
export const SET_GET_AVERAGE_SLEEP_AND_WAKE_TIME =
  "SET_GET_AVERAGE_SLEEP_AND_WAKE_TIME";
export const SET_COUNT_DAYS_WITH_SLEEP_LESS_THAN_6_HOURS =
  "SET_COUNT_DAYS_WITH_SLEEP_LESS_THAN_6_HOURS";
export const SET_COUNT_DAYS_WITH_SLEEP_MORE_THAN_8_HOURS =
  "SET_COUNT_DAYS_WITH_SLEEP_MORE_THAN_8_HOURS";
export const SET_GET_WEEKLY_AVERAGE_SLEEP = "SET_GET_WEEKLY_AVERAGE_SLEEP";
